const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// Generate PDF Challan
exports.generateChallanPDF = async (violation) => {
    return new Promise((resolve, reject) => {
        try {
            const fines = {
                'NO HELMET': 1000,
                'TRIPLE RIDING': 2000,
                'OVERSPEEDING': 5000
            };
            const amount = fines[violation.violation_type] || 500;

            const filename = `Challan_${violation.video_id}_${violation.vehicle_plate || 'UNKNOWN'}.pdf`;
            
            // For serverless: Use in-memory buffer
            const chunks = [];
            const doc = new PDFDocument();

            doc.on('data', chunk => chunks.push(chunk));
            doc.on('end', () => {
                const buffer = Buffer.concat(chunks);
                resolve({ buffer, filename, amount });
            });

            // PDF Content
            doc.fontSize(25).text('E-CHALLAN - TRAFFIC CONTROL', { align: 'center' });
            doc.moveDown();
            doc.fontSize(14).text(`Challan ID: ${Date.now()}`);
            doc.text(`Date: ${new Date().toLocaleString()}`);
            doc.moveDown();
            doc.text(`Vehicle Number: ${violation.vehicle_plate || 'UNKNOWN'}`);
            doc.text(`Violation Type: ${violation.violation_type}`);
            doc.text(`Fine Amount: INR ${amount}`);
            doc.text(`Speed Recorded: ${violation.speed_kmph || 0} kmph`);
            doc.moveDown();
            doc.text(`Confidence Score: ${(violation.confidence_score * 100).toFixed(2)}%`);
            doc.text(`Vehicle Type: ${violation.vehicle_type}`);
            doc.text(`Timestamp: ${violation.timestamp}`);
            doc.moveDown();

            doc.text('NOTICE:', { underline: true, fontSize: 12 });
            doc.fontSize(10).text('This is an automated traffic violation notice generated by AI Traffic Violation Detection System.', { width: 500 });
            doc.text('Please pay the fine within 30 days to avoid legal action.', { width: 500 });

            doc.end();
        } catch (err) {
            reject(err);
        }
    });
};

// Format violation response
exports.formatViolation = (violation) => {
    return {
        id: violation.id,
        video_id: violation.video_id,
        violation_type: violation.violation_type,
        timestamp: violation.timestamp,
        confidence_score: violation.confidence_score,
        speed_kmph: violation.speed_kmph,
        vehicle_plate: violation.vehicle_plate,
        evidence_image_path: violation.evidence_image_path,
        vehicle_type: violation.vehicle_type,
        status: violation.status,
        created_at: violation.created_at
    };
};
